### ISSUE TITLE
question - why is `@EnableEurekaServer` missing?

### ISSUE THREAD

**Issue by sridhar1982** [spring-cloud-samples/customers-stores#16]
This is a question

I do not see EurekaServer enabled, but I do see `@EnableEurekaClient` being used?
can you please clarify how the EurekaServer is configured in this example.

Thanks

**Comment by spencergibb** [comment]
[Eureka](https://github.com/spring-cloud-samples/eureka) and [config server](https://github.com/spring-cloud-samples/configserver) come from the [spring-cloud-samples](https://github.com/spring-cloud-samples) org.
