### ISSUE TITLE
Error running UI 

### ISSUE THREAD

**Issue by djbjoel** [spring-cloud-samples/customers-stores#18]
I'm getting the following error running "spring run app.groovy"

1: unable to resolve class EnableZuulProxy ,  unable to find class for annotation
 @ line 1, column 1.
   @EnableZuulProxy
   ^

2: unable to resolve class EnableDiscoveryClient ,  unable to find class for annotation
 @ line 2, column 1.
   @EnableDiscoveryClient
   ^

**Comment by spencergibb** [comment]
Seems like spring-cloud-cli is not installed according to the [readme](https://github.com/spring-cloud-samples/customers-stores#running-instructions). Follow these instructions: https://github.com/spring-cloud/spring-cloud-cli#installation
